- name: Call the Command Runner playbook for Leaf 1
  import_playbook: ../helper_playbooks/get_configuration_using_command_runner_leaf1.yaml
- name: call the Command Runner playbook for Leaf 2
  import_playbook: ../helper_playbooks/get_configuration_using_command_runner_leaf2.yaml
- name: Call the validation playbook Leaf 1
  import_playbook: ../helper_playbooks/get_cli_template_as_text_leaf1.yaml
- name: Call the validation playbook Leaf 2
  import_playbook: ../helper_playbooks/get_cli_template_as_text_leaf2.yaml
